# Generated by Django 4.2.29 on 2026-03-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('domain', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('attendance', 'Attendance'), ('exam', 'Exam'), ('course', 'Course'), ('analytics', 'Analytics')], max_length=50)),
                ('system_prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agents',
                'ordering': ['-created_at'],
            },
        ),
    ]
