# Generated by Django 4.2.29 on 2026-03-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='owner_email',
            field=models.EmailField(blank=True, default='admin@university.edu', max_length=254, null=True),
        ),
    ]
